### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by fenil-arcticgrey** [BuilderIO/builder-shopify-hydrogen#7]
I have cloned repo from https://github.com/builderio/builder-shopify-hydrogen and after changing hydrogen.config, I was trying to deploy it on hydrogen but is showing some error like this.

https://prnt.sc/tsfGdwYdhsYO

Here is my hydrogen.config file 
https://prnt.sc/yC6LkdcY4qWO

Anyone faced issue like this then help me out of this.
Thanks in advance

**Comment by steve8708** [comment]
thanks for reporting @fenil-arcticgrey - @teleaziz is actively investigating and will report back shortly

**Comment by fenil-arcticgrey** [comment]
> thanks for reporting @fenil-arcticgrey - @teleaziz is actively investigating and will report back shortly

@steve8708  @teleaziz  How much time you will take to resolve this because it is already 3 days passed

**Comment by teleaziz** [comment]
@fenil-arcticgrey and the error is a bit vague, I am not able to reproduce this, can you share any steps to reproduce it?

You can see here I pushed the code from this repo and connected it to my hydrogen store
https://github.com/teleaziz-demos/hydrogen-modern-human
Deployments logs are here:
https://github.com/teleaziz-demos/hydrogen-modern-human/actions/runs/3201340472

**Comment by fenil-arcticgrey** [comment]
@teleaziz 
I have tried to fork this repo "https://github.com/teleaziz-demos/hydrogen-modern-human" now and still facing the issue.
https://prnt.sc/2rZLIwYmpZ8x

Can you please contact me on email or call so we can solve this ASAP.
piyush@arcticgrey.com

**Comment by steve8708** [comment]
@fenil-arcticgrey it seems your issue is related to your build process as opposed to Builder https://www.awesomescreenshot.com/image/33275444?key=3c225c21d7a798351967db7be08c021a

you have a `post-resolution validation` step that is failing. perhaps the version of yarn in the code vs your CI is different? perhaps try making sure you have the same yarn version as your CI, do a yarn install, and see if your `post-resolution validation` step passes

but from the info provided, this does not look like an issue with Builder (nor can we reproduce any deployment issues with this starter from the info provided)

I would suggest debugging your CI workflow further to find a solution to your deployment

**Comment by fenil-arcticgrey** [comment]
@teleaziz  @steve8708 I checked,  there is no issue with version after successfully completed install dependencies step it is showing
error https://prnt.sc/2rQGelFEPl4-

**Comment by tylerscave** [comment]
@fenil-arcticgrey I might be chiming in a bit late, but it might just be an issue with accessing your OXYGEN_DEPLOYMENT_TOKEN in your Github secrets... I don't think this has anything to do with Builder...

More info on how to generate that token and deploy with Oxygen:
https://shopify.dev/docs/custom-storefronts/oxygen/storefronts/manage-storefronts#connect-a-hydrogen-storefront

In your repository settings, you should see something like the following (without the ENV_VAR entry) after following the steps in the documentation...


![image](https://user-images.githubusercontent.com/14061153/226019702-167665e0-3719-48ac-830a-d821dfcc346c.png)
